# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FastColuacoMain.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FastColuaco(object):
    def setupUi(self, FastColuaco):
        FastColuaco.setObjectName("FastColuaco")
        FastColuaco.resize(837, 430)
        FastColuaco.setMinimumSize(QtCore.QSize(837, 430))
        FastColuaco.setMaximumSize(QtCore.QSize(837, 430))
        self.centralwidget = QtWidgets.QWidget(FastColuaco)
        self.centralwidget.setMaximumSize(QtCore.QSize(837, 387))
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 811, 371))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(62, 20))
        self.label.setMaximumSize(QtCore.QSize(62, 20))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verChoose = QtWidgets.QComboBox(self.widget)
        self.verChoose.setMinimumSize(QtCore.QSize(104, 26))
        self.verChoose.setMaximumSize(QtCore.QSize(104, 26))
        self.verChoose.setObjectName("verChoose")
        self.verticalLayout.addWidget(self.verChoose)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.check_if_down_data = QtWidgets.QCheckBox(self.widget)
        self.check_if_down_data.setMinimumSize(QtCore.QSize(168, 23))
        self.check_if_down_data.setMaximumSize(QtCore.QSize(168, 23))
        self.check_if_down_data.setObjectName("check_if_down_data")
        self.verticalLayout.addWidget(self.check_if_down_data)
        self.check_if_comb = QtWidgets.QCheckBox(self.widget)
        self.check_if_comb.setMinimumSize(QtCore.QSize(168, 22))
        self.check_if_comb.setMaximumSize(QtCore.QSize(168, 22))
        self.check_if_comb.setObjectName("check_if_comb")
        self.verticalLayout.addWidget(self.check_if_comb)
        self.check_if_comb_release = QtWidgets.QCheckBox(self.widget)
        self.check_if_comb_release.setMinimumSize(QtCore.QSize(168, 23))
        self.check_if_comb_release.setMaximumSize(QtCore.QSize(168, 23))
        self.check_if_comb_release.setObjectName("check_if_comb_release")
        self.verticalLayout.addWidget(self.check_if_comb_release)
        self.check_if_upload = QtWidgets.QCheckBox(self.widget)
        self.check_if_upload.setMinimumSize(QtCore.QSize(168, 22))
        self.check_if_upload.setMaximumSize(QtCore.QSize(168, 22))
        self.check_if_upload.setObjectName("check_if_upload")
        self.verticalLayout.addWidget(self.check_if_upload)
        self.btn_start = QtWidgets.QPushButton(self.widget)
        self.btn_start.setMinimumSize(QtCore.QSize(169, 27))
        self.btn_start.setMaximumSize(QtCore.QSize(169, 27))
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout.addWidget(self.btn_start)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.log_window = QtWidgets.QTextEdit(self.widget)
        self.log_window.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.log_window.setObjectName("log_window")
        self.horizontalLayout.addWidget(self.log_window)
        FastColuaco.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FastColuaco)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        FastColuaco.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FastColuaco)
        self.statusbar.setObjectName("statusbar")
        FastColuaco.setStatusBar(self.statusbar)
        self.itemConfig = QtWidgets.QAction(FastColuaco)
        self.itemConfig.setObjectName("itemConfig")
        self.generalConfig = QtWidgets.QAction(FastColuaco)
        self.generalConfig.setObjectName("generalConfig")
        self.menu.addAction(self.itemConfig)
        self.menu.addAction(self.generalConfig)
        self.menubar.addAction(self.menu.menuAction())

        self.toolBar = QtWidgets.QToolBar(FastColuaco)
        self.toolBar.setObjectName("toolBar")
        FastColuaco.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(FastColuaco)
        QtCore.QMetaObject.connectSlotsByName(FastColuaco)

    def retranslateUi(self, FastColuaco):
        _translate = QtCore.QCoreApplication.translate
        FastColuaco.setWindowTitle(_translate("FastColuaco", "苍龙三国志客户端压缩工具"))
        self.label.setText(_translate("FastColuaco", "选择版本"))
        self.check_if_down_data.setText(_translate("FastColuaco", "是否下载配置表"))
        self.check_if_comb.setText(_translate("FastColuaco", "是否合并加密压缩"))
        self.check_if_comb_release.setText(_translate("FastColuaco", "是否合并加密压缩发布版"))
        self.check_if_upload.setText(_translate("FastColuaco", "是否上传测试服"))
        self.btn_start.setText(_translate("FastColuaco", "开始"))
        self.menu.setTitle(_translate("FastColuaco", "设置"))
        self.itemConfig.setText(_translate("FastColuaco", "版本设置"))
        self.generalConfig.setText(_translate("FastColuaco", "通常设置"))

